// program to add users to the database

const URL = "http://localhost:8080";

const username = ['haldar.apratim005@gmail.com',
    'mustafabdullha@gmail.com',
    'panditsoham83@gmaip.com',
    'abhigyan.kulavi2004@gmail.com',
    'chatterjeesanchari33@gmail.com',
    'ankur.mandal.129@gmail.com',
    'chakrabortyspandan045@gmail.com',
    'saikatdey2100@gmail.com',
    'gracykumari14@gmail.com',
    'aditya25022002@gmail.com',
    '22shreyatrivedi@gmail.com',
    'trishutanjiro@gmail.com',
    'krish7.kalwani@gmail.com',
    'sbagchi.mjm@gmail.com',
    'cmrityunjoy450@gmail.com',
    'pratiksamanta14@gmail.com',
    'suthirthasoma@gmail.com',
    'mandaltanishree@gmail.com',
    'btechtanjil15@gmail.com',
    'soumabhadas3105@gmail.com',
    'rayjishnn@gmail.com',
    'ditsukundu08@gmail.com',
    'aryansaha222005@gmail.com',
    'aritrabiswas7003@gmail.com',
    'swarnenduboral@gmail.com',
    'aryansengupta75@gmail.com',
    'sayantannayek45@gmail.com',
    'aishikmaiti@gmail.com',
    'mohitshaw2404@gmail.com',
    'subh.03sphs@gmail.com',
    'ruchikasharma030504@gmail.com',
    'rimsahashinjini@gmail.com',
    'debarghya2016@gmail.com',
    'rajdevpal14@gmail.com',
    'rparna652@gmail.com',
    'parthibkarak2004@gmail.com',
    'thearchismans@gmail.com',
    'krish.sarkar12345@gmail.com',
    'ureachedayan@gmail.com',
    'barshanachatterjee@gmail.com',
    'ashmitapaul436@gmail.com',
    'bisurock0101@gmail.com',
    'prarthitakuri@gmail.com',
    'stutisamanta04@gmail.com',
    'supravajha909@gmail.com',
    'utkarsha04ghosh@gmail.com',
    'srishtiraj05102004@gmail.com',
    'shinjanbhatta@gmail.com',
    'onjoydeep@gmail.com',
    'pushanseth3@gmail.com',
    'rishavecr2897@gmail.com',
    'araj672004@gmail.com',
    'anjansuman80@gmail.com',
    'ankitshaw6933@gmail.com',
    'ramyaniroy52@gmail.com',
    'deypoulami37@gmail.com',
    'gourabbandhu229@gmail.com',
    'gourabbandhu229@gmail.com',
    'ayusmanguru9@gmail.com',
    'apodder506@gamil.com',
    'shyantan5@gmail.com',
    'adrijamethodist@gmail.com',
    'sahasam5652@gmail.com',
    'bijoyroykgp2@gmail.com',
    'rusha9076@gmail.com',
    'rajnandanichaudhary196@gmail.com',
    'mahek6suhan@gmail.com',
    'debanshudolui3@gmail.com',
    'debanshudolui3@gmail.com',
    'sarthaksantrabe@gmail.com',
    'rounakchaudhury@gmail.com',
    'sumit891084@gmail.com',
    'satwikkhan@gmail.com',
    'adarsh25prasad@gmail.com',
    'soumilimukherjee04@gmail.com',
    'keshavchandan2307@gmail.com',
    'suranjanam987@gmail.com',
    'ashishshekharash@gmail.com',
    'sayanmaji0408@gmail.com',
    'dipayansadhu573@gmail.com',
    'aichchandramouli@gmail.com',
    'shouvikdasshoumo@gmail.com',
    'divyanshuchoudhary24022004@gmail.com',
    'annweshanaha2005@gmail.com',
    'souhardyarayiemece@gmail.com',
    'aritramukherjee2710@gmail.com',
    'arighnabhattacharjee003@gmail.com',
    'agnikmaity12@gmail.com',
    'karmakarkabita70@gmail.com',
    'sreejanibanik@gmail.com',
    'srthkmkhrj@gmail.com',
    'aditya.drive2005@gmail.com',
    'swastik.das2005@gmail.com',
    'meghnasaha2005@gmail.com',
    'ghoshsoumili2005@gmail.com',
    'ab3424525@gmail.com',
    'bhattacharjeeabhirup23@gmail.com',
    'bhattacharjeeabhirup23@gmail.com',
    'adakankana648@gamil.com',
    'rrighten@gmail.com',
    'antariksinha2017@gmail.com',
    'anuvabmunshi@gmail.com',
    'chakrabortyanushka991@gmail.com',
    'snehabanerjee1977@gmail.com',
    'soumodeepnath2003@gmail.com',
    'swastikadey3011@gmail.com',
    'roydebjit2402@gmail.com',
    'oisheesarkar7@gmail.com',
    'maitraarunima88@gmail.com',
    'aharshisinha2020@gmail.com',
    'sarbatrikijana@gmail.com',
    'srijapal2005@gmail.com',
];
const fullname = ['Apratim Haldar',
    'Md Mustafa Abdullha',
    'Soham pandit',
    'Abhigyan Kulavi', 
    'Sanchari Chatterjee', 
    'ANKUR MANDAL',
    'Spandan Chakraborty', 
    'Saikat Dey',
    'Gracy kumari', 
    'Aditya Kumar',
    'Shreya Trivedi',
    'Trishan Manna', 
    'Krish J Kalwani',
    'Snigdharup Bagchi', 
    'Mrityunjoy Chakraborty', 
    'Pratik Samanta', 
    'Suthirtha Dey',
    'Tanushree Mandal', 
    'Md Tanjil Hussain', 
    'Soumabha Das', 
    'Jishnu Ray', 
    'Ditsu Kundu', 
    'ARYAN SAHA',
    'Aritra Biswas',
    'Swarnendu Boral',
    'Aryan Sengupta',
    'Sayantan Nayek',
    'AISHIK MAITI', 
    'MOHIT SHAW',
    'Subhadeep Pal',
    'Ruchika Sharma', 
    'Shinjini Saha',
    'DEBARGHYA CHOWDHURY', 
    'RAJDEV PAL', 
    'PARNA ROY',
    'Parthib karak',
    'Archisman Saha', 
    'KRISHNA KANTA SARKAR', 
    'Ayantika Chakraborty', 
    'Barshana Chatterjee',
    'Aishmita Paul', 
    'Biswayan Roy',
    'Prarthita Kuri', 
    'Stuti Samanta',
    'SUPRAVA JHA', 
    'Utkarsha Ghosh',
    'Srishti Raj',
    'Shinjan Bhatta',
    'Joydeep Sarkar', 
    'Pushan Seth', 
    'Rishave Ghosh',
    'Amit Raj',
    'Anjan Suman',
    'Ankit Shaw', 
    'Ramyani Roy', 
    'Poulami Dey', 
    'Gourab Bandhu', 
    'GOURAB BANDHU', 
    'Ayusman Guru',
    'Amit Podder', 
    'Shyantan Kundu',
    'Adrija Ghosh', 
    'Samriddha Saha',
    'Sreenjoy Roy',
    'Ruchika Sharma', 
    'Rajnandani Chaudhary', 
    'Mahek Khosla', 
    'Debanshu Dolui', 
    'Debanshu Dolui', 
    'Sarthak Santra',
    'Rounak Chaudhury', 
    'Sumit Chatterjee', 
    'Satwik Khan', 
    'Adarsh Raj',
    'Soumili Mukherjee',
    'Keshav chandan', 
    'Suranjana Mondal',
    'Ashish Shekhar', 
    'Sayan Maji',
    'Dipayan Sadhu',
    'Chandramouli Aich',
    'Shouvik Das',
    'Divyanshu Choudhary',
    'Annwesha Naha',
    'Souhardya Ray',
    'Aritra Mukherjee',
    'Arighna Bhattacharjee',
    'AGNIK MAITY',
    'Sarthak Karmakar', 
    'Sreejani Banik',
    'Sarthak Mukherjee', 
    'Aditya Narayan Dikshit', 
    'Swastik Das',
    'Meghna Saha', 
    'SOUMILI GHOSH', 
    'Ankita Biswas', 
    'Abhirup Bhattacharjee', 
    'Abhirup Bhattacharjee', 
    'Ankana adak',
    'Mainak Biswas',
    'Antarik Sinha', 
    'Anuvab Munshi', 
    'Anushka Chakraborty', 
    'Sneha Banerjee', 
    'Soumodeep Nath',
    'Swastika Dey', 
    'DEBJIT ROY', 
    'Oishee Sarkar', 
    'Arunima Maitra',
    'Aharshi Sinha',
    'Sarbatriki Jana', 
    'Srija Pal' ];

function AddUser(username, fullname) {
    fetch(`${URL}/addUser`, {
    method: "POST",
    crossDomain: true,
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
      "Access-Control-Allow-Origin": "*",
    },
    body: JSON.stringify({
      username: username,
      fullname: fullname,
      points: 0
    }),
  })
    .then((res) => res.json())
    .then((data) => {
      console.log(`Added ${data.data.fullname}`)
    });
}

var count = 0;

for (let i = 0; i < username.length; i++) {
    AddUser(username[i], fullname[i]);
    count++;
}

console.log("Total users: ", count);